import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV file generated by the C++/CUDA program
data = pd.read_csv("transfer_speed.csv")

# Create a plot comparing pageable and pinned memory transfer speeds
plt.figure()
plt.plot(data['Size_Bytes'], data['Pageable_HtoD_MBps'], marker='o', linestyle='-', label="Pageable HtoD")
plt.plot(data['Size_Bytes'], data['Pageable_DtoH_MBps'], marker='s', linestyle='-', label="Pageable DtoH")
plt.plot(data['Size_Bytes'], data['Pinned_HtoD_MBps'], marker='^', linestyle='--', label="Pinned HtoD")
plt.plot(data['Size_Bytes'], data['Pinned_DtoH_MBps'], marker='d', linestyle='--', label="Pinned DtoH")

plt.xscale('log', base=2)
plt.xlabel('Transfer Size (Bytes)')
plt.ylabel('Bandwidth (MB/s)')
plt.title('GPU Memory Transfer Speed: Pageable vs. Pinned')
plt.grid(True, which="both", linestyle="--", linewidth=0.5)
plt.legend()
plt.tight_layout()
plt.savefig("transfer_speed.png")
plt.show()

# Compute and print the peak transfer speeds for each curve
peak_pageable_htod = data['Pageable_HtoD_MBps'].max()
peak_pageable_dtoh = data['Pageable_DtoH_MBps'].max()
peak_pinned_htod = data['Pinned_HtoD_MBps'].max()
peak_pinned_dtoh = data['Pinned_DtoH_MBps'].max()

print("Peak Pageable Host-to-Device Bandwidth: {:.2f} MB/s".format(peak_pageable_htod))
print("Peak Pageable Device-to-Host Bandwidth: {:.2f} MB/s".format(peak_pageable_dtoh))
print("Peak Pinned Host-to-Device Bandwidth: {:.2f} MB/s".format(peak_pinned_htod))
print("Peak Pinned Device-to-Host Bandwidth: {:.2f} MB/s".format(peak_pinned_dtoh))
